// Only run locally or in CI
// eslint-disable-next-line import/no-extraneous-dependencies
const checker = require("license-checker");

const config = {
  start: ".",
  excludePackages: [
    "paho-mqtt@1.1.0",
    "rx-lite@4.0.8",
    "rx-lite-aggregates@4.0.8",
  ].join(";"),
  onlyAllow: [
    "CC0-1.0",
    "PDDL-1.0",
    "SAX-PD",
    "Unlicense",
    "UNLICENSED",
    "Public Domain",

    "AFL-1.1",
    "AFL-1.2",
    "AFL-2.0",
    "AFL-2.1",
    "AFL-3.0",
    "Apache-1.0",
    "Apache-1.1",
    "Apache-2.0",
    "Artistic-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSD-3-Clause-Attribution",
    "BSD-3-Clause-Clear",
    "BSD-2-Clause-FreeBSD",
    "BSD-3-Clause-LBNL",
    "BSD-2-Clause-NetBSD",
    "BSD-3-Clause-No-Nuclear-License",
    "BSD-3-Clause-No-Nuclear-License-2014",
    "BSD-3-Clause-No-Nuclear-Warranty",
    "BSD-4-Clause",
    "BSD-4-Clause-UC",
    "0BSD",
    "BSD",

    "CC-BY-3.0",
    "CC-BY-4.0",

    "DSDP",
    "ECL-2.0",
    "ISC",
    "MIT",
    "X11",
    "WTFPL",
    "OLDAP-2.2.2",
    "OLDAP-1.1",
    "OLDAP-1.2",
    "OLDAP-1.3",
    "OLDAP-1.4",
    "OLDAP-2.0",
    "OLDAP-2.0.1",
    "OLDAP-2.1",
    "OLDAP-2.2",
    "OLDAP-2.2.1",
    "OLDAP-2.3",
    "OLDAP-2.4",
    "OLDAP-2.5",
    "OLDAP-2.6",
    "OLDAP-2.7",
    "OLDAP-2.8",
    "PHP-3.0",
    "PHP-3.01",
    "Python-2.0",
    "Zlib",
    "zlib-acknowledgement",
    "XFree86-1.1",
    "W3C-20150513",
    "W3C-19980720",
    "W3C",
    "OpenSSL",
    "Naumen",
    "JasPer-2.0",
    "EFL-1.0",
    "EFL-2.0",
    "MIT-advertising",
    "MIT-enna",
    "MIT-CMU",
    "APSL-1.0",
    "Beerware",
    "CECILL-1.0",
    "CECILL-1.1",
    "CECILL-2.0",
    "CECILL-2.1",
    "CECILL-B",
    "CNRI-Jython",
    "CNRI-Python",
    "CNRI-Python-GPL-Compatible",
    "Condor-1.1",
    "MIT-feh",
    "FTL",
    "ICU",
    "Ruby",
    "Sendmail",
    "iMatix",
    "xinetd",
    "ZPL-1.1",
    "ZPL-2.0",
    "ZPL-2.1",
    "TCL",

    "LGPL-2.0",
    "LGPL-2.1",
    "LGPL-2.1+",
    "LGPL-3.0",
    "LGPL-3.0+",
    "MPL-2.0",
    "MPL-1.0",
    "MPL-1.1",
    "MPL-2.0-no-copyleft-exception",
    "CDDL-1.0",
    "CDDL-1.1",
    "MS-PL",
    "Sleepycat",
    "ClArtistic",
    "Artistic-1.0",
    "Artistic-1.0-Perl",
    "Artistic-1.0-cl8",
    "APSL-1.1",
    "APSL-1.2",
    "APSL-2.0",
    "LPPL-1.0",
    "LPPL-1.1",
    "LPPL-1.2",
    "LPPL-1.3a",
    "LPPL-1.3c",
    "CPAL-1.0",
    "CATOSL-1.1",
    "CUA-OPL-1.0",
    "ErlPL-1.1",
    "gSOAP-1.3b",
    "IPL-1.0",
    "NASA-1.3",
    "NOSL",
    "Nokia",
    "RHeCos-1.1",
    "RSCPL",
    "SugarCRM-1.1.3",
    "SISSL",
    "SISSL-1.2",
    "SPL-1.0",
    "Zimbra-1.3",
    "Zimbra-1.4",
    "BitTorrent-1.0",
    "BitTorrent-1.1",
    "CECILL-C",
    "Motosoto",
    "MS-LRL",
    "Watcom-1.0",
    "YPL-1.0",
    "YPL-1.1",
    "Interbase-1.0",

    "OFL-1.1",

    "ODC-By-1.0",
  ].join(";"),
};

checker.init(config, (err, __) => {
  if (err) {
    throw err;
  }
});
